# Generated by Django 5.1.2 on 2024-10-14 03:36

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', banjo.models.StringField(default='')),
                ('hint', banjo.models.StringField(default='')),
                ('likes', banjo.models.IntegerField(default=0)),
                ('difficulty', banjo.models.IntegerField(default=0)),
                ('correct_percentage', banjo.models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
