# Generated by Django 5.1.2 on 2024-10-15 07:12

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='answer',
            field=banjo.models.StringField(default=''),
        ),
    ]
