# Generated by Django 5.1.2 on 2024-10-15 07:13

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quotes_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='difficulty',
            field=banjo.models.StringField(default=''),
        ),
    ]
