# Generated by Django 5.1.2 on 2024-10-15 07:17

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_quotes_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='archive',
            field=banjo.models.StringField(default=''),
        ),
    ]
