# Generated by Django 5.1.2 on 2024-10-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quotes_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='archive',
        ),
    ]
