# Generated by Django 5.1.2 on 2024-10-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quotes_correct_quotes_guesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='correct_percentage',
        ),
    ]
