# Generated by Django 5.1.2 on 2024-10-23 07:45

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_quotes_correct_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='correct_percentage',
            field=banjo.models.FloatField(default=0.0),
        ),
    ]
