# Generated by Django 5.1.2 on 2024-10-23 09:47

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quotes_correct_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='category',
            field=banjo.models.StringField(default=''),
        ),
    ]
